apiVersion: v1
kind: Secret
metadata:
  name: recipica-secrets
  namespace: recipica
type: Opaque
stringData:
  DB_USER: "recipica_user"
  DB_PASSWORD: "change_me"
  MYSQL_ROOT_PASSWORD: "change_me_root"
  JWT_SECRET: "change_me_jwt_secret"
  EMAIL_USER: "change_me@example.com"
  EMAIL_PASSWORD: "change_me_email_password"
